version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: docker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - postgres
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    env_file: ./.env
    restart: always

volumes:
  postgres-data: