version: "3"

services:
  app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    env_file: ./.env
    restart: always
